// Generated by CoffeeScript 1.3.3
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    return res.send('hello world!');
  });

  app.listen(3000);

  console.log('listening on port 3000');

}).call(this);
